// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Apollo from "./Apollo.mjs";
import * as Categories from "./Categories.mjs";
import * as AddCategory from "./AddCategory.mjs";
import * as Client from "@apollo/client";

function App(Props) {
  return React.createElement(Client.ApolloProvider, {
              client: Apollo.client,
              children: React.createElement("div", {
                    className: "App"
                  }, React.createElement("h1", undefined, "Bom dia"), React.createElement("div", undefined, React.createElement(AddCategory.make, {}), React.createElement(Categories.make, {})))
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
